#!/bin/bash
# chkconfig: 2345 20 80
. /etc/init.d/functions

name=d1
base_dir=/mc/instances/$name
start() {
	cd $base_dir
	nohup java -Xms512M -Xmx1G -jar $name.jar --nogui &
}

stop() {
	cd $base_dir
	mcrcon -H 127.0.0.1 -P 21011 -p panda142857 stop
	sleep 5
	ps aux |grep $name.jar |grep -v grep  |awk '{print $2}' |while read pid ; do
		kill -9 $pid
	done
}
conn() {
	cd $base_dir
	mcrcon -H 127.0.0.1 -P 21011 -p panda142857  $1
}

case "$1" in 
    conn)
       conn
       ;;
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
