#!/bin/bash
# chkconfig: 2345 20 80
. /etc/init.d/functions
name=s1

get_rcon_port(){
	local area=$1
	case $area in 
		bc)  echo 26577;;
		hub) echo 11000;;
		d1)  echo 21001;;
		d2)  echo 21002;;
		s1)  echo 31001;;
		s2)  echo 31002;;
		*)   echo 0;;
	esac
}

base_dir=/mc/instances/$name
mcrcon_pre="/mc/mcrcon/mcrcon -H 127.0.0.1 -P $(get_rcon_port $name) -p panda142857"

mc_exist(){
	local jar_name=$1
	ps aux |grep $jar_name |grep -v grep >/dev/null
}
status(){
	mc_exist $name.jar
	if [ $? -eq 0 ]; then
		echo "$name running"
	else
		echo "$name stopped"
	fi
}
start() {
	cd $base_dir
	nohup java -Xms1G -Xmx2G -jar $name.jar --nogui &
}

stop() {
	cd $base_dir
	$mcrcon_pre stop
	for i in $(seq 1 10); do 
		mc_exist $name.jar
		if [ $? -eq 0 ] ; then 
			return 
		else
			sleep 1
		fi
	done
	ps aux |grep $name.jar |grep -v grep  |awk '{print $2}' |while read pid ; do
		kill -9 $pid
	done
}
conn() {
	cd $base_dir
	$mcrcon_pre  $1
}

case "$1" in 
    conn)
       conn
       ;;
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
	    status
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
